### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by gheeenrique** [gerencianet/gn-api-prestashop#1]
Olá, estou com um erro no modulo, fiz a instalação como orienta o tutorial, mas olha o erro que obtenho no momento da compra:
http://prntscr.com/b004ma
Obrigado e parabéns pelo modulo que está em desenvolvimento.

**Comment by jpferreira123** [comment]
Olá @gheeenrique ,

Você poderia disponibilizar um link para que eu possa realizar uma compra de testes e verificar o erro? Caso tenha interesse, me adicione no skype: joao.ferreira.gerencianet ou envie um ticket através de sua conta Gerencianet com as informações.

Obrigado pelo reconhecimento e contamos com você para ajudar a otimizar o módulo.
