### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by vega-internet** [gerencianet/gn-api-prestashop#2]
Olá, após instalar ativar e configurar o módulo de pagamento de vocês em minha loja Prestashop 1.6.1.6... recebo erro 500 ao tentar finalizar uma compra (todos os passos do carrinho de compras vão bem até chegar na última parte, ao clicar no botão do GerenciaNet para pagar, sou redirecionado para a url: https://www.MEUDOMINIO.com.br/module/gerencianet/payment  e à partir dai já recebo erro 500....

**Erro informado na tela:**
500 Server Error
Oops, something went wrong.

Try to refresh this page or feel free to contact us if the problem persists.

Após isso ativei o "modo desenvolvedor" no meu Prestashop e dessa forma consegui as seguintes informações de erro:

Notice: Use of undefined constant _PS_CLOUDFLARE_SSL - assumed '_PS_CLOUDFLARE_SSL' in /home/MEU-USUARIO/public_html/classes/Tools.php on line 411

Warning: Cannot modify header information - headers already sent by (output started at /home/MEU-USUARIO/public_html/classes/Tools.php:411) in/home/MEU-USUARIO/public_html/classes/controller/FrontController.php on line 1000

Warning: Cannot modify header information - headers already sent by (output started at /home/MEU-USUARIO/public_html/classes/Tools.php:411) in/home/MEU-USUARIO/public_html/classes/controller/FrontController.php on line 1001

Warning: Cannot modify header information - headers already sent by (output started at /home/MEU-USUARIO/public_html/classes/Tools.php:411) in/home/MEU-USUARIO/public_html/classes/exception/PrestaShopException.php on line 37
[PrestaShopException]
Property Customer->document is empty
at line 909 in file classes/ObjectModel.php
904. }
905.
906. $message = $this->validateField($field, $this->$field);
907. if ($message !== true) {
908. if ($die) {
909. throw new PrestaShopException($message);
910. }
911. return $error_return ? $message : false;
912. }
913. }
914.
ObjectModelCore->validateFields - [line 246 - classes/ObjectModel.php]
ObjectModelCore->getFields - [line 47 - modules/gerencianet/controllers/front/payment.php]
GerencianetPaymentModuleFrontController->initContent - [line 189 - classes/controller/Controller.php]
ControllerCore->run - [line 367 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 28 - index.php]

Aguardo ajuda, pois já cancelei com o Mercado Pago e agora fiquei com a loja parada devido à isso, estou apostando na qualidade do serviços de vocês, por isso migrei, espero ter feito um escolha feliz.

Se precisar de qualquer informação, adicional, basta me solicitar, abraço e muito obrigado desde já!

**Comment by chuckbnorris** [comment]
@vega-internet 

Me chamo Tiago e sou da equipe de Consultoria Técnica em Integrações da Gerencianet.

Conforme resposta a seu [issue anterior](https://github.com/gerencianet/gn-api-prestashop/issues/3), esta questão descrita já foi solucionada?

Em caso negativo, peço por gentileza que efetue login em sua conta Gerencianet e abra um ticket para interagir com o nosso suporte. Desta forma, iremos visualizar requisições em sua API, dentre outras informações.

Caso precise de orientações sobre como abrir tickets, por favor, acesse: https://dev.gerencianet.com.br/docs/fale-conosco

Qualquer coisa, estou à disposição.
