### ISSUE TITLE
ERRO FATAL MODULO PRESTASHOP 1.6.1.6

### ISSUE THREAD

**Issue by vegainternet** [gerencianet/gn-api-prestashop#3]
Olá amigos, estou implementando mais uma loja virtual em Prestashop, e fui instalar o módulo de vocês (que baxei no github) e após enviar pra instalar o módulo, retornou o seguinte erro:

[PrestaShop] Fatal error in module file :/home/MEU-USUARIO/public_html/config/smarty.config.inc.php:
Cannot redeclare smartyDieObject() (previously declared in /home/MEU-USUARIO/public_html/lojavirtual/config/smarty.config.inc.php:87)

Então, sai e voltei no painel, e ele funciona normal, porém se eu clicar em módulos, recebo o erro novamente, ou seja, estragou a parte de módulos da loja, o que pode ser???

Com o modo DEBUG ativo, tenho o seguinte erro:

Fatal error: Cannot redeclare smartyDieObject() (previously declared in /home/MEU-USUARIO/public_html/lojavirtual/config/smarty.config.inc.php:87) in /home/MEU-USUARIO/public_html/config/smarty.config.inc.php on line 90
[PrestaShop] Fatal error in module file :/home/MEU-USUARIO/public_html/config/smarty.config.inc.php:
Cannot redeclare smartyDieObject() (previously declared in /home/MEU-USUARIOm/public_html/lojavirtual/config/smarty.config.inc.php:87)

AGUARDO AJUDA, OBRIGADO DESDE JÁ!

**Comment by chuckbnorris** [comment]
@vegainternet 

Me chamo Tiago e sou da equipe de Consultoria Técnica em Integrações da Gerencianet.

Analisando este erro, observei que a função smartyDieObject() é do próprio Prestashop, e não de nosso módulo (veja [este link](https://github.com/Shagshag/prestashop-documentation/blob/master/1.6.0.4/function.smartyDieObject.md)). Por isso, não se trata de um erro conhecido e até então, "novo" para o nosso módulo.

Podemos ajudá-lo, mas precisaremos de sua colaboração. É ideal que você efetue login em sua conta Gerencianet e abra um ticket para interagir com o nosso suporte.

Caso precise de orientações sobre como abrir tickets, por favor, acesse: https://dev.gerencianet.com.br/docs/fale-conosco

Qualquer coisa, estou à disposição.
